[images]
  remote_images = [
    "https://ext.same-assets.com/664063133/380314192.jpeg",
    "https://ext.same-assets.com/569546920/3926702543.gif",
    "https://ext.same-assets.com/569546920/132285589.gif"
  ]

[build]
  command = "bun install && bun run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "21.7.3"
  BUN_VERSION = "latest"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "next"
  command = "bun dev"
  targetPort = 3000
  port = 8888