[images]
  remote_images = [
    "https://ext.same-assets.com/664063133/380314192.jpeg",
    "https://ext.same-assets.com/569546920/3926702543.gif",
    "https://ext.same-assets.com/569546920/132285589.gif"
  ]

[build]
  command = "npm install && npm run build"  # Switched from bun to npm
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "21.7.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "next"
  command = "npm run dev"  # Switched from bun to npm
  targetPort = 3000
  port = 8888
